version: '3.8'
services:
  web:
    container_name: crypto-pm2-web
    build: .
    ports:
      - 5000:5000
    restart: always
    logging:
      options:
        max-size: "5m"
        max-file: "3"